log:
  Level: info

telegram:
  Token: 

mongo:
  Uri: 
  Database: memes

inline:
  PageSize: 20

storage-service:
  Uri: http://storage-service:7001

user-account:
  StaticUuid: f6a3e8a0-c3b8-45af-a2d3-7bbe2879e0e6